name : "Multi Event Pipeline/workflow"

on: 
    push: # event : whenever a push is made to the repository on the master branch 
        branches:
            - master
            - test
    pull_request:
        branches:
            - master 
jobs: 
    on-push: #job name
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
            - name : "Running on push" #step 1
              run: echo "Running on master push"